name: Nox

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Setup Nox
      uses: daisylb/setup-nox@v2.1.0
    - name: Run Nox
      run: |
        nox -s reformat lint test
